#!/bin/bash

./run docker-compose -f docker-compose-tracer.yml build

if [ "$?" -ne "0" ]; then
  echo "Failed to build Tracer DB"
  exit 1
fi

./run docker-compose -f docker-compose-tracer.yml pull validator deploy-evm proxy
