version: "3"

services:
  solana:
    container_name: solana
    image: neonlabsorg/solana:${SOLANA_REVISION:-v1.7.9-resources}
    environment:
      SOLANA_URL: http://solana:8899
      RUST_LOG: solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
    hostname: solana
    ports:
      - 127.0.0.1:8899:8899
    expose:
      - "8899"
      - "9900"
      - "8900"
      - "8001"
      - "8001-8009/udp"
    networks:
      - net
    healthcheck:
      # Must be available from outside (calling without -u causes premature result)
      test: [ CMD-SHELL, "solana cluster-version -u http://solana:8899" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
      
  cli_builder:
    container_name: cli_builder
    build:
      context: ./evm_builder
      dockerfile: Dockerfile
    image: evm_builder:latest
    environment:
       NEON_REVISION: ${NEON_REVISION:-latest}
    volumes:
       - ./neon-evm/evm_loader/:/opt/evm_loader/
    working_dir: /opt/evm_loader/cli
    entrypoint: cargo build --release
      
  evm_builder:
    container_name: evm_builder
    build:
      context: ./evm_builder
      dockerfile: Dockerfile
    image: evm_builder:latest
    environment:
       NEON_REVISION: ${NEON_REVISION:-latest}
    volumes:
       - ./neon-evm/evm_loader/:/opt/evm_loader/
    working_dir: /opt/evm_loader
    entrypoint: >
      bash -c "cd program && /opt/evm_loader/ci_checks.sh
      && cargo build --release
      && cargo build-bpf --features no-logs"

  evm_loader:
    container_name: evm_loader
    image: neonlabsorg/evm_loader:${EVM_LOADER_REVISION:-latest}
    environment:
      - SOLANA_URL=http://solana:8899
    networks:
      - net
    depends_on:
      solana:
        condition: service_healthy
    command: bash -c "create-test-accounts.sh 1 && deploy-evm.sh"
    volumes:
      - ./neon-evm/evm_loader/target/release/neon-cli:/opt/neon-cli
      - ./neon-evm/evm_loader/target/deploy/evm_loader.so:/opt/evm_loader.so

  postgres:
    container_name: postgres
    image: postgres:14.0
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
    hostname: postgres
    healthcheck:
      test: [ CMD-SHELL, "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
    expose:
      - "5432"
    networks:
      - net

  proxy:
    container_name: proxy
    image: neonlabsorg/proxy:${PROXY_REVISION:-latest}
    environment:
      SOLANA_URL: http://solana:8899
      POSTGRES_DB: neon-db
      POSTGRES_USER: neon-proxy
      POSTGRES_PASSWORD: neon-proxy-pass
      NEW_USER_AIRDROP_AMOUNT: 100
      CONFIG: ci
    hostname: proxy
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 127.0.0.1:9090:9090
    expose:
      - "9090"
    networks:
      - net
    entrypoint: proxy/run-test-proxy.sh
    volumes:
      - ./neon-evm/evm_loader/target/release/neon-cli:/spl/bin/neon-cli
      - ./proxy-model.py:/opt

  proxy-test:
    container_name: proxy-test
    image: neonlabsorg/proxy:${PROXY_REVISION:-latest}
    environment:
      SOLANA_URL: http://solana:8899
      PROXY_URL: http://proxy:9090/solana
      EVM_LOADER: 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
      EXTRA_GAS: 100000
    hostname: proxy-test
    depends_on:
      - proxy
    networks:
      - net
    entrypoint: proxy/deploy-test.sh test_eth_sendRawTransaction.py
    volumes:
      - ./neon-evm/evm_loader/target/release/neon-cli:/spl/bin/neon-cli
      - ./proxy-model.py:/opt

networks:
  net:

