version: '3'

x-base-builder: &x-base-builder
   build:
      context: .
      dockerfile: Dockerfile
   image: evm-builder
   working_dir: /opt/neon-dev-env
   volumes:
         - .:/opt/neon-dev-env
   
services:
   solana:
      container_name: solana
      image: neonlabsorg/solana:v1.7.9-resources
      environment:
         - SOLANA_URL=http://localhost:8899
         - RUST_LOG=solana_runtime::system_instruction_processor=trace,solana_runtime::message_processor=debug,solana_bpf_loader=debug,solana_rbpf=debug
      expose:
         - "8899"
         - "9900"
         - "8900"
         - "8001"
         - "8001-8009/udp"
      network_mode: host

   build-evm:
      <<: *x-base-builder
      command: ./build-evm.sh
      
   deploy-evm:
      <<: *x-base-builder
      command: ./deploy-evm.sh local
      network_mode: host
      
   proxy:
      container_name: neon-proxy
      build:
         context: ./proxy-model.py/
         dockerfile: Dockerfile
      environment:
         CONFIG: local
         NEW_USER_AIRDROP_AMOUNT: 10
      env_file: neon-config.env
      working_dir: /opt/
      command: ./proxy/run-proxy.sh
      network_mode: host
      expose:
         - "9090"

